version: '3'

services:
  db:
    image: postgres:14-alpine
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - ./data/docker/volumes/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}

volumes:
  mysql_data:
